// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADQKujzR6JjT-h_dvPd-q1e49aMcaDFLc',
    appId: '1:721509314048:web:16823a0917e59db6aaf2e5',
    messagingSenderId: '721509314048',
    projectId: 'finpro-84832',
    authDomain: 'finpro-84832.firebaseapp.com',
    storageBucket: 'finpro-84832.firebasestorage.app',
    measurementId: 'G-0MKM8JCXWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgsu2dUSsoNAfrqH-ZQEJ9mAfKgL1-y-Y',
    appId: '1:721509314048:android:351c5722d93351acaaf2e5',
    messagingSenderId: '721509314048',
    projectId: 'finpro-84832',
    storageBucket: 'finpro-84832.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC0cd9oZipe6hWCq4vnnALCUL9t35tfFA',
    appId: '1:721509314048:ios:3eec1fd8740c9d98aaf2e5',
    messagingSenderId: '721509314048',
    projectId: 'finpro-84832',
    storageBucket: 'finpro-84832.firebasestorage.app',
    iosBundleId: 'com.example.finProNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC0cd9oZipe6hWCq4vnnALCUL9t35tfFA',
    appId: '1:721509314048:ios:3eec1fd8740c9d98aaf2e5',
    messagingSenderId: '721509314048',
    projectId: 'finpro-84832',
    storageBucket: 'finpro-84832.firebasestorage.app',
    iosBundleId: 'com.example.finProNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADQKujzR6JjT-h_dvPd-q1e49aMcaDFLc',
    appId: '1:721509314048:web:d7f3808695b24a3caaf2e5',
    messagingSenderId: '721509314048',
    projectId: 'finpro-84832',
    authDomain: 'finpro-84832.firebaseapp.com',
    storageBucket: 'finpro-84832.firebasestorage.app',
    measurementId: 'G-9GN74F8RH6',
  );
}
